### ISSUE TITLE
Using $_GET['page'] without properly sanitization.

### ISSUE THREAD

**Issue by widoz** [churchthemes/widget-importer-exporter#16]
Within the `/includes/page.php` we use the following markup to generate the exporter btn.

```
<a href="<?php echo esc_url( admin_url( basename( $_SERVER['PHP_SELF'] ) . '?page=' . $_GET['page'] . '&export=1&wie_export_nonce=' . wp_create_nonce('wie_export') ) ); ?>" 
     id="wie-export-button" 
     class="button button-primary">
           <?php echo esc_html_x( 'Export Widgets', 'button', 'widget-importer-exporter' ); ?>
</a>
```

Should the `$_GET['page']` sanitized? 
The value of the page may be compromised in someway. We can use `sanitize_key` function since it's strip all character non included in pattern `/[^a-z0-9_\-]/` but I'm not quite sure about the context.

**Comment by stevengliebe** [comment]
I'm not sure this is an issue since that button is only rendered on /wp-admin/tools.php?page=widget-importer-exporter. The value will always be the same. I could hard-code "widget-importer-exporter" in the link instead of using $_GET['page'] but the latter seems more ideal in case, for whatever reason, the page slug ever changes names.
